### ISSUE TITLE
Support ActionFPS-Game log format

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/game-log-parser#3]

**Comment by ScalaWilliam** [comment]
https://github.com/ScalaWilliam/ActionFPS/issues/297

**Comment by lucasgautheron** [comment]
Changes:
 * IP replaced by https://github.com/ActionFPS/ActionFPS-Game/blob/fd43752b49996172280c8716ec0102bbd2697fad/source/src/server.h#L245 into [...]

**Comment by ScalaWilliam** [comment]
formatstring(identity)("%s:%s:%s", group.id, userid, hostname);
            else
                formatstring(identity)("%s:%s", userid, hostname);


Should the ordering be the other way round? Looking at logs hostnames won't be aligned nicely

**Comment by lucasgautheron** [comment]
Alright, edited!
https://github.com/ActionFPS/ActionFPS-Game/blob/master/source/src/server.h#L245
https://github.com/ActionFPS/ActionFPS-Game/commit/34e45952bb29bd540651b8d62fbaff4b3d39446d
